
 input {
   beats {
     port => 5044
   }
 }

 filter {
         json {
           source => "message"
         }
         mutate {
           add_field => { "sample" => "Hello world, from %{host}" }
         }
 }

 output {
     stdout { codec => json }
     elasticsearch {
       hosts => ["http://elasticsearch:9200"]
       index => "logstash-nginx-%{+YYYY.MM.dd}"  # Использовать другое имя индекса
       action => "create"  # Явно указать операцию create вместо index

     }

 }
