spring.datasource.url=jdbc:postgresql://postgresdb:5432/productsdb
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.batch.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.batch.jdbc.table-prefix=BATCH_

management.endpoints.web.exposure.include=beans,env,health,info,metrics,mappings,prometheus
management.endpoint.health.show-details=always
management.health.probes.enabled=true

logging.level.com.ivanfranchin.moviesapi=DEBUG


# Включение метрик Spring Batch
management.metrics.enable.spring.batch=true
management.metrics.enable.spring.batch.job=true
management.metrics.enable.spring.batch.step=true
management.metrics.enable.spring.batch.item.read=true
management.metrics.enable.spring.batch.item.write=true
management.metrics.enable.spring.batch.item.process=true

# Настройки Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Дополнительные настройки метрик
management.metrics.distribution.percentiles-histogram.spring.batch.job=true
management.metrics.distribution.percentiles-histogram.spring.batch.step=true
management.metrics.distribution.percentiles.spring.batch.job=0.5,0.75,0.95,0.99
management.metrics.distribution.percentiles.spring.batch.step=0.5,0.75,0.95,0.99

# Чтобы приложение не завершалось после выполнения задания
spring.batch.job.restartable=true
