input {
  beats {
    port => 5044
    host => "0..0.0"
  }
}

filter {
  # Обработка логов приложения
  if [docker][container][labels][com_docker_compose_service] == "app" {
    json {
      source => "message"
      target => "log"
    }

    # Добавляем метаданные
    mutate {
      add_field => {
        "container_id" => "%{[docker][container][id]}"
        "container_name" => "%{[docker][container][name]}"
        "service_name" => "batch-processing-app"
      }
    }

    # Парсим timestamp
    date {
      match => ["ts", "ISO8601"]
      target => "@timestamp"
    }

    # Удаляем избыточные поля
    mutate {
      remove_field => ["ts", "host", "input", "agent", "ecs", "log"]
    }
  }

  # Обработка логов nginx
  else if [fileset][module] == "nginx" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }

    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
  }
}

output {
  # Для логов приложения
  if [docker][container][labels][com_docker_compose_service] == "app" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "app-logs-%{+YYYY.MM.dd}"
    }
  }
  # Для логов nginx
  else if [fileset][module] == "nginx" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
  }
  # Для остальных логов
  else {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "other-logs-%{+YYYY.MM.dd}"
    }
  }

  # Вывод в консоль для отладки
  stdout {
    codec => rubydebug
  }
}
